config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :members
  resources :purchases
  resources :discounts
  resources :plans
  resources :products
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => 'confirmations',
    :passwords => 'passwords' }
  namespace :api do
    post 'plan' => "events#plan"
    post 'plans' => "events#plans"
    post 'payment' => "events#payment"
    post 'confirm' => "events#confirm"
    post 'resend' => "events#resend"
    post 'reset' => "events#reset"
    post 'delete' => "events#delete"
    post 'invoice' => "events#invoice"
  end
  root 'billing#index', as: :billing
  get "/:page" => "static#show"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :plan
  belongs_to :user
  belongs_to :discount, optional: true

  monetize :rebate_cents
  monetize :total_cents
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action do 
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:plan_id, :user_id, :discount_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plan_id %>
    <%= form.text_field :plan_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :discount_id %>
    <%= form.text_field :discount_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Editing Invoice</h2>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <span>
                            <div class="container">
                                <div class="row">
                                    <%= link_to 'Show', @invoice, :class => "btn btn-primary" %>
                                    <%= link_to 'Back', invoices_path, :class => "btn btn-primary" %>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 mt-4 text-center">
                                        <%= render 'form', invoice: @invoice %>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/invoices/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h2 class="m-0 text-dark">Invoices</h2>
      </div>
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <span>
              <div class="container">
                <div class="row">
                  <%= link_to 'New Invoice', new_invoice_path, :class => "btn btn-primary" %>
                </div>
                <div class="row">
                  <div class="col-md-12 mt-4 text-center">
                    <table>
                      <thead>
                        <tr>
                          <th>User</th>
                          <th>Plan</th>
                          <th>Price</th>
                          <th>Discount</th>
                          <th>Rebate</th>
                          <th>Total</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @invoices.each do |invoice| %>
                        <tr>
                          <td><%= invoice.user.email %></td>
                          <td><%= invoice.plan.name %></td>
                          <td><%= invoice.plan.price %></td>
                          <td><%= invoice.discount.nil? ? "" : invoice.discount.name %></td>
                          <td><%= invoice.rebate %></td>
                          <td><%= invoice.total %></td>
                          <td><%= link_to 'Show', invoice, :class => "btn btn-primary" %></td>
                          <td><%= link_to 'Edit', edit_invoice_path(invoice), :class => "btn btn-primary" %></td>
                          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/invoices/new.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">New Invoice</h2>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <span>
                            <div class="container">
                                <div class="row">
                                    <%= link_to 'Back', invoices_path, :class => "btn btn-primary" %>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 mt-4 text-center">
                                        <%= render 'form', invoice: @invoice %>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/invoices/show.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h2 class="m-0 text-dark">Invoice</h2>
      </div>
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <span>
              <div class="container">
                <div class="row">
                    <%= link_to 'Edit', edit_invoice_path(@invoice), :class => "btn btn-primary" %> <%= link_to 'Back', discounts_path, :class => "btn btn-primary" %>
                </div>
                <div class="row">
                  <p>
                    <strong>Id:</strong>
                    <%= @invoice.id %>
                  </p>
                  <p>
                    <strong>User:</strong>
                    <%= @invoice.user.email %>
                  </p>
                  <p>
                    <strong>Plan:</strong>
                    <%= @invoice.plan.name %>
                  </p>
                  <p>
                    <strong>Discount:</strong>
                    <%= @invoice.discount.name %>
                  </p>
                  <p>
                    <strong>Price:</strong>
                    <%= @invoice.plan.price %>
                  </p>
                  <p>
                    <strong>Rebate:</strong>
                    <%= @invoice.rebate %>
                  </p>
                  <p>
                    <strong>Total:</strong>
                    <%= @invoice.total %>
                  </p>
                </div>
              </div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>