config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :members
  resources :purchases
  resources :discounts
  resources :plans
  resources :products
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => 'confirmations',
    :passwords => 'passwords' }
  namespace :api do
    post 'plan' => "events#plan"
    post 'plans' => "events#plans"
    post 'payment' => "events#payment"
    post 'confirm' => "events#confirm"
    post 'resend' => "events#resend"
    post 'reset' => "events#reset"
    post 'delete' => "events#delete"
    post 'invoice' => "events#invoice"
  end
  root 'billing#index', as: :billing
  get "/:page" => "static#show"
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :product
    monetize :price_cents
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action do 
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name,  :description, :product_id, :price, :duration)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.select :product_id, Product.all.collect {|x| [x.name, x.id]}, {}, :multiple => false %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Editing Plan</h2>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <span>
                            <div class="container">
                                <div class="row">
                                    <%= link_to 'Show', @plan, :class => "btn btn-primary" %>
                                    <%= link_to 'Back', plans_path, :class => "btn btn-primary" %>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 mt-4 text-center">
                                        <%= render 'form', plan: @plan %>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/plans/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h2 class="m-0 text-dark">Plans</h2>
      </div>
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <span>
              <div class="container">
                <div class="row">
                  <%= link_to 'New Plan', new_plan_path, :class => "btn btn-primary" %>
                </div>
                <div class="row">
                  <div class="col-md-12 mt-4 text-center">
                    <table>
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Product</th>
                          <th>Price</th>
                          <th>Duration</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @plans.each do |plan| %>
                        <tr>
                          <td><%= plan.name %></td>
                          <td><%= plan.product.name %></td>
                          <td><%= plan.price %></td>
                          <td><%= plan.duration %></td>
                          <td><%= link_to 'Show', plan, :class => "btn btn-primary" %></td>
                          <td><%= link_to 'Edit', edit_plan_path(plan), :class => "btn btn-primary" %></td>
                          <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/plans/new.html.erb
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">New Plan</h2>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <span>
                            <div class="container">
                                <div class="row">
                                    <%= link_to 'Back', plans_path, :class => "btn btn-primary" %>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 mt-4 text-center">
                                        <%= render 'form', plan: @plan %>
                                    </div>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/plans/show.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h2 class="m-0 text-dark">Plan</h2>
      </div>
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <span>
              <div class="container">
                <div class="row">
                    <%= link_to 'Edit', edit_plan_path(@plan), :class => "btn btn-primary" %> <%= link_to 'Back', plans_path, :class => "btn btn-primary" %>
                </div>
                <div class="row">
                  <p>
                    <strong>Name:</strong>
                    <%= @plan.name %>
                  </p>
                  <p>
                    <strong>Description:</strong>
                    <%= @plan.description %>
                  </p>
                  <p>
                    <strong>Product:</strong>
                    <%= @plan.product.name %>
                  </p>
                </div>
              </div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>