config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :members
  resources :purchases
  resources :discounts
  resources :plans
  resources :products
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => 'confirmations',
    :passwords => 'passwords' }
  namespace :api do
    post 'plan' => "events#plan"
    post 'plans' => "events#plans"
    post 'payment' => "events#payment"
    post 'confirm' => "events#confirm"
    post 'resend' => "events#resend"
    post 'reset' => "events#reset"
    post 'delete' => "events#delete"
    post 'invoice' => "events#invoice"
  end
  root 'billing#index', as: :billing
  get "/:page" => "static#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discount.rb
class Discount < ApplicationRecord
    belongs_to :plan
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :plan
  belongs_to :user
  belongs_to :discount, optional: true

  monetize :rebate_cents
  monetize :total_cents
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :product
    monetize :price_cents
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :invoice
  belongs_to :plan
  monetize :amount_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable

  has_one :member, dependent: :destroy

  after_create :init_member

  def serializable_hash(options = nil) 
    super(options).merge(confirmed_at: confirmed_at).except("admin")
  end

  def init_member
    self.create_member!
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController 
    before_action :authenticate_user
    skip_before_action :verify_authenticity_token
    private
      def authenticate_user
        true
      end
  
      def unauthorize
        head status: :unauthorized
        return false
      end
  end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action do 
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name,  :description, :product_id, :price, :duration)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    layout 'static'
    def show
        render params[:page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.erb
<footer class="main-footer">
  <strong>Copyright © 2019 Your Stuff.</strong>
  All rights reserved.
</footer>

app/views/layouts/_header.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to "Home", billing_path, class: "nav-link" %>
      </li>
      <% if current_user && current_user.admin %>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Plans", plans_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Discounts", discounts_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Invoices", invoices_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Purchases", purchases_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <%= link_to "Members", members_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
<!-- Right navbar links -->
    <% if current_user %>
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <%= link_to "Logout", destroy_user_session_path, method: "delete", class: "nav-link" %>
      </li>
    </ul>
    <% end %>
  </nav>

app/views/layouts/_sidebar.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <span class="brand-text font-weight-light">Standup App</span>
  </a>
<!-- Sidebar -->
  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 652px;"><div class="sidebar" style="min-height: 652px; overflow: hidden; width: auto; height: 652px;">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="http://placehold.it/160x160" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">User Name</a>
      </div>
    </div>
<!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Activity
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="./index.html" class="nav-link active">
                <i class="far fa-circle nav-icon"></i>
                <p>Mine</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Feed</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byoi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
  </head>

  <body class="sidebar-mini">
    <div class="wrapper">
      <%= render partial: "layouts/header" %>
      <div class="content-wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byoi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="sidebar-mini">
    <div class="wrapper">
      <div class="content-wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>